### ISSUE TITLE
Group commands

### ISSUE THREAD

**Issue by oxyshad** [totoff974/jeedom-JeeMySensors#1]
Hi
Great plugin, however I've noticed that after inclusion each device's command create a new device on jeedom for that command which is confusing.
I think that they should be grouped by device ID. 

Regards

**Comment by totoff974** [comment]
Hello thank you.  precisely I wanted each "sensor" to be a unique equipment in order to use the voice assistants.  Thus we can distinguish each "sensor" also the "node" is a separate equipment.  I think it helps to be more flexible.  I can have a "node" in a room, to which I have installed several "sensors" in different rooms, which I can assign under jeedom.

**Comment by oxyshad** [comment]
Yes it is a good idea if you have a node with sensors in different locations, but you still can rename them in jeedom even when on the same node. And what about battery voltage sensor for example, it will create a seperate device.
Is it possible to add a config option to choose betwwen seperate or group sensors /node ?

Regards

**Comment by totoff974** [comment]
Hello,

Regarding the battery it is attached to the "node". When you add a component mysensors (by activating automatic inclusion in the plugin), the plugin will add automatic the "node" with its information, namely, its type (repeater or not), its version, the version of the sketch and the state of the battery.
Then the plugin will look at the "sensors" and create equipment for each of them with their commands and / or info.

Adding an option group or not seems difficult, so I wanted to distinguish the sensors in equipment jeedom precisely to be able to treat them correctly and use other plugins like voice assistants (essential to have a separate equipment to drive them) .
If you want to group your sensors (equipment) in one it is necessary in this case to use a "virtual".

Also if you have a "sensor" battery (multimeter), to differentiate the battery of the node you will find it in the form of equipment with an info.

For me the "node" is the physical equipment (an arduino nano) and the "sensors" of electronic components (relays, probes ... etc ...)
