### ISSUE TITLE
Compatibilité avec debian bullseye

### ISSUE THREAD

**Issue by tplet** [totoff974/jeedom-JeeMySensors#3]
Bonjour,

En installant le plugin sur un jeedom monté sur un Debian Bullseye, j'ai pu rencontrer plusieurs problèmes liés aux dépendances.
Les packages suivants ne sont plus disponibles sur cette version de Debian : 
* python-serial
* python-requests
* python-pyudev

Pour corriger le problème, je tente de corriger les dépendances comme suit : 
```
wget https://bootstrap.pypa.io/pip/2.7/get-pip.py
python get-pip.py
rm get-pip.py
echo 70 > /tmp/dependancy_JeeMySensors_in_progress
python -m pip install requests serial pyudev
```

A la place de ``apt-get install -y python-serial python-requests python-pyudev``, dans les fichiers ``install.sh`` et ``install_apt.sh``, mais il me reste encore à résoudre la vérification de la bonne installation des dépendances dans le fichier ``JeeMySensors.class.php``.

Avez-vous rencontré ce type de problème sur cette distribution également ?

**Comment by tplet** [comment]
Finalement, pour solutionner le problème, j'ai installé manuellement pip ainsi que les dépendances tout en gardant les modifications ci-dessous pour shunter la vérification de dépendance.
En parallèle j'ai tenté de rendre compatible les scripts pour Python3 mais en vain.

Ce n'est pas la solution idéal cependant.

```
curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
sudo python2 get-pip.py
rm get-pip.py
pip install serial requests pyudev
```

**Comment by totoff974** [comment]
bonsoir,
le plugin n'est pas compatible python3 pour le moment.
cordialement,

**Comment by tplet** [comment]
Ok pour la compatibilité python3.

Je ferme l'issue. Elle contient le contournement pour l'installation sur Debian Bullseye.
J'espère que cela servira à d'autres.
